### ISSUE TITLE
Why is VDI talking to minio through the proxy?

### ISSUE THREAD

**Issue by Foxcapades** [VEuPathDB/vdi-service#295]
And why did minio timeout?

Example Log:
```
2024-05-13 04:49:43.621 (wid:slim-cache-db) [rid:     ] ERROR vdi.daemon.reconciler.ReconcilerInstance - failure running reconciler for cache-db
 io.minio.errors.InvalidResponseException: Non-XML response from server. Response code: 502, Content-Type: text/html; charset=iso-8859-1, body: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request <em><a href="/vdi-prod">GET&nbsp;/vdi-prod</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p></p>
</body></html>

	at io.minio.S3Base$1.onResponse(S3Base.java:652) ~[service.jar:?]
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) ~[service.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
```

**Comment by Foxcapades** [comment]
From Kris:
> So minio-prod.uga/penn.apidb.org points directly to prod webservers, and it goes through apache that way. We could route through container networks if we really wanted to, just more effort and more differences between dev/qa and prod
